backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"       # πού αποθηκεύονται τα αρχεία στο repo
public_folder: "/assets/uploads"     # πώς φαίνονται στο site

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
